# 默认训练配置
data_dir: /mnt/data/publicData/MICCAI19_SCARED/train/dataset7/keyframe4/image_02/data/
batch_size: 4  # 增加批次大小以提高GPU利用率
num_epochs: 100
scale_factor: 0.25  # 进一步减小到1/8
max_size: [256, 320]  # [H, W] 严格控制输入尺寸
sequence_length: 3

# 网络选择
use_fast_network: false  # 使用快速网络（深度可分离卷积）
use_improved_network: true  # 使用改进的网络

# 学习率
lr_generator: 0.0002
lr_discriminator: 0.0002

# 改进的损失权重
lambda_recon: 2.0        # 增加重构损失权重
lambda_guide: 0.3        # 降低伪标签权重  
lambda_sparse: 0.1       # 稀疏性损失
lambda_smooth: 0.5       # 增加平滑性损失
lambda_temporal: 0.3     # 时间一致性损失
lambda_gan: 0.05         # 降低GAN损失
lambda_intrinsic_reg: 0.2  # 内在颜色正则化
lambda_shading_reg: 0.3    # 光照正则化
lambda_intrinsic: 0.1   # 内在颜色一致性损失
lambda_mask: 0.1        # Mask正则化损失

# SVT参数
svt_rank: 10
svt_threshold: 0.1

# 分解方法选择
decomposition_method: endosrr  # 可选: endosrr, physical, svt
use_pseudo_labels: true  # 是否使用伪标签
use_iterative: false  # 是否使用迭代分解（训练时建议false以加速）

# 训练优化
gradient_clip: 1.0  # 梯度裁剪
mixed_precision: false  # 混合精度训练（加速）
accumulation_steps: 1  # 梯度累积步数

# 日志和保存
log_interval: 10
save_interval: 10
checkpoint_dir: ./checkpoints
log_dir: ./logs

# 推理设置
inference:
  device: cuda
  use_temporal_consistency: true
  target_size: [512, 640]  # [H, W]